server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root!1234
    jpa:
      show-sql: true
      properties:
        hibernate.format_sql: true
  devtools:
    add-properties: false
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
